services:
    api-gateway:
        profiles: ["app"]
        container_name: api-gateway
        build: services/api-gateway
        expose:
            - "3000"
        networks:
            - frontend-network
            - backend-network
        restart: unless-stopped

    svc-auth:
        profiles: ["app"]
        container_name: svc-auth
        build: services/svc-auth
        networks:
            - backend-network
        volumes:
            - svc_auth_secrets:/secrets:ro
        depends_on:
            auth-db:
                condition: service_healthy
            vault-agent-auth:
                condition: service_completed_successfully
        restart: unless-stopped

    svc-user:
        profiles: ["app"]
        container_name: svc-user
        build: services/svc-user
        networks:
            - backend-network
        volumes:
            - svc_user_secrets:/secrets:ro
            - profile_pictures:/var/www/avatars
        depends_on:
            user-db:
                condition: service_healthy
            vault-agent-user:
                condition: service_completed_successfully
        restart: unless-stopped

    svc-interview-store:
        profiles: ["app"]
        container_name: svc-interview-store
        build: services/svc-interview-store
        networks:
            - backend-network
        volumes:
            - svc_interview_store_secrets:/secrets:ro
        depends_on:
            interview-store-db:
                condition: service_healthy
            vault-agent-interview-store:
                condition: service_completed_successfully
        restart: unless-stopped

    svc-grading:
        profiles: ["app"]
        container_name: svc-grading
        build: services/svc-grading
        networks:
            - backend-network
        volumes:
            - svc_grading_secrets:/secrets:ro
        depends_on:
            grading-db:
                condition: service_healthy
            vault-agent-grading:
                condition: service_completed_successfully
        restart: unless-stopped

    # svc-serialization:
    #     container_name: svc-serialization
    #     build: services/svc-serialization
    #     networks:
    #         - backend-network
    #     restart: unless-stopped

    # dev-front:
    #     container_name: dev-front
    #     ports:
    #         - "5173:5173"


    prometheus:
        profiles: ["app"]
        container_name: prometheus
        image: prom/prometheus:latest
        command:
            - "--config.file=/etc/prometheus/prometheus.yml"
            - "--storage.tsdb.path=/prometheus"
        ports:
            - "127.0.0.1:9090:9090"
        volumes:
            - ./infrastructure/monitoring/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
            - ./infrastructure/monitoring/prometheus/alerts.yml:/etc/prometheus/alerts.yml:ro
            - prometheus_data:/prometheus
        networks:
            - backend-network
        restart: unless-stopped

    cadvisor:
        profiles: ["app"]
        container_name: cadvisor
        image: gcr.io/cadvisor/cadvisor:latest
        expose:
            - "8080"
        volumes:
            - /:/rootfs:ro
            - /var/run:/var/run:rw
            - /sys:/sys:ro
            - /var/lib/docker/:/var/lib/docker:ro
        networks:
            - backend-network
        restart: unless-stopped

    grafana:
        profiles: ["app"]
        container_name: grafana
        image: grafana/grafana-oss:latest
        ports:
            - "127.0.0.1:3001:3000"
        environment:
            GF_SECURITY_ADMIN_USER: admin
            GF_SECURITY_ADMIN_PASSWORD_FILE: /run/secrets/grafana_admin_password
            GF_USERS_ALLOW_SIGN_UP: "false"
            GF_AUTH_ANONYMOUS_ENABLED: "false"
        volumes:
            - grafana_data:/var/lib/grafana
            - grafana_secrets:/run/secrets:ro
            - ./infrastructure/monitoring/grafana/provisioning:/etc/grafana/provisioning:ro
            - ./infrastructure/monitoring/grafana/dashboards:/var/lib/grafana/dashboards:ro
        networks:
            - backend-network
        depends_on:
            vault-agent-grafana:
                condition: service_completed_successfully
            prometheus:
                condition: service_started
        restart: unless-stopped

    frontend-certgen:
        profiles: ["app"]
        container_name: frontend-certgen
        image: alpine:3.20
        user: "0:0"
        entrypoint: ["/bin/sh", "/certgen.sh"]
        volumes:
            - frontend_tls:/tls
            - ./frontend/nginx/tools/certgen.sh:/certgen.sh:ro
        restart: "no"

    frontend:
        profiles: ["app"]
        container_name: frontend
        build:
            context: ./frontend
            dockerfile: Dockerfile
        ports:
            - "443:443"
        networks:
            - frontend-network
            - backend-network
        depends_on:
            frontend-certgen:
                condition: service_completed_successfully
        volumes:
            - frontend_tls:/etc/nginx/ssl
            - profile_pictures:/var/www/avatars
        restart: unless-stopped

    auth-db:
        profiles: ["app"]
        container_name: auth-db
        build: infrastructure/databases/auth-db
        networks:
            - backend-network
        env_file:
            - infrastructure/databases/auth-db/.env_auth_db
        environment:
            POSTGRES_PASSWORD_FILE: /run/secrets/auth_db_superuser_password
        volumes:
            - auth_db:/var/lib/postgresql/data
            - auth_db_secrets:/run/secrets:ro
        depends_on:
            vault-agent-auth-db:
                condition: service_completed_successfully
        restart: unless-stopped


    user-db:
        profiles: ["app"]
        container_name: user-db
        build: infrastructure/databases/user-db
        networks:
            - backend-network
        expose:
            - "5432"
        env_file:
            - infrastructure/databases/user-db/.env_user_db
        environment:
            POSTGRES_PASSWORD_FILE: /run/secrets/user_db_superuser_password
        volumes:
            - user_db:/var/lib/postgresql/data
            - user_db_secrets:/run/secrets
        depends_on:
            vault-agent-user-db:
                condition: service_completed_successfully
        restart: unless-stopped

    interview-store-db:
        profiles: ["app"]
        container_name: interview-store-db
        build: infrastructure/databases/interview-store-db
        expose:
            - "5432"
        networks:
            - backend-network
        env_file:
            - infrastructure/databases/interview-store-db/.env_interview_store_db
        environment:
            POSTGRES_PASSWORD_FILE: /run/secrets/interview_store_db_superuser_password
        volumes:
            - interview_store_db:/var/lib/postgresql/data
            - interview_store_db_secrets:/run/secrets
        depends_on:
            vault-agent-interview-store-db:
                condition: service_completed_successfully
        restart: unless-stopped

    grading-db:
        profiles: ["app"]
        container_name: grading-db
        build: infrastructure/databases/grading-db
        networks:
            - backend-network
        env_file:
            - infrastructure/databases/grading-db/.env_grading_db
        environment:
            POSTGRES_PASSWORD_FILE: /run/secrets/grading_db_superuser_password
        volumes:
            - grading_db:/var/lib/postgresql/data
            - grading_db_secrets:/run/secrets:ro
        depends_on:
            vault-agent-grading-db:
                condition: service_completed_successfully
        restart: unless-stopped

    # serialization-db:
    #     container_name: serialization-db
    #     build: infrastructure/databases/serialization-db
    #     env_file:
    #         - infrastructure/databases/serialization-db/.env_serialization_db
    #     volumes:
    #         - serialization_db:/var/lib/postgresql
    #     secrets:
    #         - serialization_db_password
    #     networks:
    #         - backend-network
    #     restart: unless-stopped

    # rabbitmq:
    #     container_name: rabbitmq
    #     build: infrastructure/rabbitmq
    #     networks:
    #         - backend-network
    #     restart: unless-stopped

    vault-certgen:
        profiles: ["vault"]
        container_name: vault_certgen
        image: alpine:3.20
        entrypoint: ["/bin/sh", "-lc"]
        command: ["sh /certgen.sh"]
        environment:
            VAULT_UID: "100"
            VAULT_GID: "1000"
        volumes:
            - vault_tls:/tls
            - ./infrastructure/vault/tools/scripts/certgen.sh:/certgen.sh:ro
        networks:
            - backend-network
        restart: "no"

    vault:
        profiles: ["vault"]
        container_name: vault
        build: infrastructure/vault
        entrypoint: ["/bin/sh", "-lc"]
        command: ["sh /vault/tools/wait_tls.sh"]
        networks:
            - backend-network
        ports:
            - "127.0.0.1:8200:8200"
        volumes:
            - vault_data:/vault/file
            - vault_tls:/vault/tls:ro
            - vault_logs:/vault/logs
        depends_on:
            - vault-certgen
        restart: unless-stopped

        healthcheck:
            test:
                [
                    "CMD-SHELL",
                    "export VAULT_ADDR=https://127.0.0.1:8200 VAULT_CACERT=/vault/tls/ca.crt; vault status -format=json | jq -e '.initialized==true and .sealed==false' >/dev/null",
                ]
            interval: 10s
            timeout: 5s
            retries: 5

    vault-bootstrap:
        profiles: ["vault"]
        container_name: vault-bootstrap
        image: hashicorp/vault:2.0.0
        entrypoint: ["/bin/sh", "-lc"]
        command: ["sh /vault/bootstrap/scripts/bootstrap.sh"]
        environment:
            VAULT_ADDR: "https://vault:8200"
            VAULT_CACERT: "/vault/tls/ca.crt"
        tmpfs:
            - /vault/file
            - /vault/logs
        volumes:
            - vault_tls:/vault/tls:ro
            - vault_init:/vault/bootstrap/vault_init

            - svc_auth_vault_creds:/vault/bootstrap/creds-out/auth
            - svc_user_vault_creds:/vault/bootstrap/creds-out/user
            - svc_interview_store_vault_creds:/vault/bootstrap/creds-out/interview-store
            - svc_grading_vault_creds:/vault/bootstrap/creds-out/grading
            - auth_db_vault_creds:/vault/bootstrap/creds-out/auth-db
            - user_db_vault_creds:/vault/bootstrap/creds-out/user-db
            - interview_store_db_vault_creds:/vault/bootstrap/creds-out/interview-store-db
            - grading_db_vault_creds:/vault/bootstrap/creds-out/grading-db
            - grafana_vault_creds:/vault/bootstrap/creds-out/grafana

            - ./infrastructure/vault/tools/scripts/bootstrap.sh:/vault/bootstrap/scripts/bootstrap.sh
            - ./infrastructure/vault/updates/services.txt:/vault/bootstrap/services_updates/services.txt
            - ./infrastructure/vault/policies:/vault/bootstrap/policies:ro
        networks:
            - backend-network
        user: "0:0"
        depends_on:
            - vault
            - vault-certgen
        restart: "no"

    vault-seed:
        profiles: ["vault"]
        container_name: vault-seed
        image: hashicorp/vault:2.0.0
        user: "0:0"
        entrypoint: ["/bin/sh", "-lc"]
        command: ["sh /bootstrap/tools/seed.sh"]
        env_file:
            - ./infrastructure/vault/.env_seed_local
        environment:
            VAULT_ADDR: "https://vault:8200"
            VAULT_CACERT: "/vault/tls/ca.crt"
        tmpfs:
            - /vault/file
            - /vault/logs
        volumes:
            - vault_tls:/vault/tls:ro
            - vault_init:/bootstrap/secrets:ro
            - ./infrastructure/vault/tools/scripts/seed.sh:/bootstrap/tools/seed.sh:ro
            - ./infrastructure/vault/updates/seed-manifest.txt:/bootstrap/tools/seed-manifest.txt
        networks:
            - backend-network
        depends_on:
            - vault-certgen
            - vault
            - vault-bootstrap
        restart: "no"


    vault-agent-auth:
        profiles: ["app"]
        container_name: vault-agent-auth
        image: hashicorp/vault:2.0.0
        user: "0:0"
        entrypoint: ["/bin/vault"]
        command: ["agent", "-config=/vault/agent/agent.hcl"]
        environment:
            VAULT_ADDR: "https://vault:8200"
            VAULT_CACERT: "/vault/tls/ca.crt"
        tmpfs:
            - /vault/file
            - /vault/logs
        volumes:
            - vault_tls:/vault/tls:ro
            - svc_auth_vault_creds:/vault/creds:ro
            - svc_auth_secrets:/secrets
            - ./infrastructure/vault/agents/auth:/vault/agent:ro
        networks:
            - backend-network
        restart: no

    vault-agent-user:
        profiles: ["app"]
        container_name: vault-agent-user
        image: hashicorp/vault:2.0.0
        user: "0:0"
        entrypoint: ["/bin/vault"]
        command: ["agent", "-config=/vault/agent/agent.hcl"]
        environment:
            VAULT_ADDR: "https://vault:8200"
            VAULT_CACERT: "/vault/tls/ca.crt"
        tmpfs:
            - /vault/file
            - /vault/logs
        volumes:
            - vault_tls:/vault/tls:ro
            - svc_user_vault_creds:/vault/creds:ro
            - svc_user_secrets:/secrets
            - ./infrastructure/vault/agents/user:/vault/agent:ro
        networks:
            - backend-network
        restart: no

    vault-agent-interview-store:
        profiles: ["app"]
        container_name: vault-agent-interview-store
        image: hashicorp/vault:2.0.0
        user: "0:0"
        entrypoint: ["/bin/vault"]
        command: ["agent", "-config=/vault/agent/agent.hcl"]
        environment:
            VAULT_ADDR: "https://vault:8200"
            VAULT_CACERT: "/vault/tls/ca.crt"
        tmpfs:
            - /vault/file
            - /vault/logs
        volumes:
            - vault_tls:/vault/tls:ro
            - svc_interview_store_vault_creds:/vault/creds:ro
            - svc_interview_store_secrets:/secrets
            - ./infrastructure/vault/agents/interview-store:/vault/agent:ro
        networks:
            - backend-network
        restart: no

    vault-agent-grading:
        profiles: ["app"]
        container_name: vault-agent-grading
        image: hashicorp/vault:2.0.0
        user: "0:0"
        entrypoint: ["/bin/vault"]
        command: ["agent", "-config=/vault/agent/agent.hcl"]
        environment:
            VAULT_ADDR: "https://vault:8200"
            VAULT_CACERT: "/vault/tls/ca.crt"
        tmpfs:
            - /vault/file
            - /vault/logs
        volumes:
            - vault_tls:/vault/tls:ro
            - svc_grading_vault_creds:/vault/creds:ro
            - svc_grading_secrets:/secrets
            - ./infrastructure/vault/agents/grading/agent.hcl:/vault/agent/agent.hcl:ro
            - ./infrastructure/vault/agents/grading/templates:/vault/templates:ro
        networks:
            - backend-network
        restart: "no"

    vault-agent-auth-db:
        profiles: ["app"]
        container_name: vault-agent-auth-db
        image: hashicorp/vault:2.0.0
        user: "0:0"
        entrypoint: ["/bin/vault"]
        command: ["agent", "-config=/vault/agent/agent.hcl"]
        environment:
            VAULT_ADDR: "https://vault:8200"
            VAULT_CACERT: "/vault/tls/ca.crt"
        tmpfs:
            - /vault/file
            - /vault/logs
        volumes:
            - vault_tls:/vault/tls:ro
            - auth_db_vault_creds:/vault/creds:ro
            - auth_db_secrets:/secrets
            - ./infrastructure/vault/agents/auth-db/agent.hcl:/vault/agent/agent.hcl:ro
            - ./infrastructure/vault/agents/auth-db/templates:/vault/templates:ro
        networks:
            - backend-network
        restart: "no"

    vault-agent-user-db:
        profiles: ["app"]
        container_name: vault-agent-user-db
        image: hashicorp/vault:2.0.0
        user: "0:0"
        entrypoint: ["/bin/vault"]
        command: ["agent", "-config=/vault/agent/agent.hcl"]
        environment:
            VAULT_ADDR: "https://vault:8200"
            VAULT_CACERT: "/vault/tls/ca.crt"
        tmpfs:
            - /vault/file
            - /vault/logs
        volumes:
            - vault_tls:/vault/tls:ro
            - user_db_vault_creds:/vault/creds:ro
            - user_db_secrets:/secrets
            - ./infrastructure/vault/agents/user-db/agent.hcl:/vault/agent/agent.hcl:ro
            - ./infrastructure/vault/agents/user-db/templates:/vault/templates:ro
        networks:
            - backend-network
        restart: "no"
    
    vault-agent-interview-store-db:
        profiles: ["app"]
        container_name: vault-agent-interview-store-db
        image: hashicorp/vault:2.0.0
        user: "0:0"
        entrypoint: ["/bin/vault"]
        command: ["agent", "-config=/vault/agent/agent.hcl"]
        environment:
            VAULT_ADDR: "https://vault:8200"
            VAULT_CACERT: "/vault/tls/ca.crt"
        tmpfs:
            - /vault/file
            - /vault/logs
        volumes:
            - vault_tls:/vault/tls:ro
            - interview_store_db_vault_creds:/vault/creds:ro
            - interview_store_db_secrets:/secrets
            - ./infrastructure/vault/agents/interview-store-db/agent.hcl:/vault/agent/agent.hcl:ro
            - ./infrastructure/vault/agents/interview-store-db/templates:/vault/templates:ro
        networks:
            - backend-network
        restart: "no"

    vault-agent-grading-db:
        profiles: ["app"]
        container_name: vault-agent-grading-db
        image: hashicorp/vault:2.0.0
        user: "0:0"
        entrypoint: ["/bin/vault"]
        command: ["agent", "-config=/vault/agent/agent.hcl"]
        environment:
            VAULT_ADDR: "https://vault:8200"
            VAULT_CACERT: "/vault/tls/ca.crt"
        tmpfs:
            - /vault/file
            - /vault/logs
        volumes:
            - vault_tls:/vault/tls:ro
            - grading_db_vault_creds:/vault/creds:ro
            - grading_db_secrets:/run/secrets
            - ./infrastructure/vault/agents/grading-db/agent.hcl:/vault/agent/agent.hcl:ro
            - ./infrastructure/vault/agents/grading-db/templates:/vault/templates:ro
        networks:
            - backend-network
        restart: "no"
    
    vault-agent-grafana:
        profiles: ["app"]
        container_name: vault-agent-grafana
        image: hashicorp/vault:2.0.0
        user: "0:0"
        entrypoint: ["/bin/vault"]
        command: ["agent", "-config=/vault/agent/agent.hcl"]
        environment:
            VAULT_ADDR: "https://vault:8200"
            VAULT_CACERT: "/vault/tls/ca.crt"
        tmpfs:
            - /vault/file
            - /vault/logs
        volumes:
            - vault_tls:/vault/tls:ro
            - grafana_vault_creds:/vault/creds:ro
            - grafana_secrets:/run/secrets
            - ./infrastructure/vault/agents/grafana:/vault/agent:ro
        networks:
            - backend-network
        restart: "no"

networks:
    frontend-network:
        driver: bridge
    backend-network:
        driver: bridge
volumes:
    auth_db:
        name: auth_db_volume
    user_db:
        name: user_db_volume
    interview_store_db:
        name: interview_store_db_volume
    grading_db:
        name: grading_db_volume
    serialization_db:
        name: serialization_db_volume
    monitoring:
        name: monitoring_volume
    ingress:
        name: ingress_volume
    profile_pictures:
        name: profile_pictures_shared_volume
    prometheus_data:
        name: prometheus_data_volume
    grafana_data:
        name: grafana_data_volume
    
    # SECRETS VOLUMES FOR VAULT AGENTS AND SERVICES/DB
    svc_auth_secrets:
        name: svc_auth_secrets_volume
    svc_user_secrets:
        name: svc_user_secrets_volume
    svc_interview_store_secrets:
        name: svc_interview_store_secrets_volume
    svc_grading_secrets:
        name: svc_grading_secrets_volume
    auth_db_secrets:
        name: auth_db_secrets_volume
    user_db_secrets:
        name: user_db_secrets_volume
    interview_store_db_secrets:
        name: interview_store_db_secrets_volume
    grading_db_secrets:
        name: grading_db_secrets_volume
    grafana_secrets:
        name: grafana_secrets_volume

    # VAULT CREDS VOLUMES
    svc_auth_vault_creds:
        name: svc_auth_vault_creds_volume
    svc_user_vault_creds:
        name: svc_user_vault_creds_volume
    svc_interview_store_vault_creds:
        name: svc_interview_store_vault_creds_volume
    svc_grading_vault_creds:
        name: svc_grading_vault_creds_volume
    auth_db_vault_creds:
        name: auth_db_creds_volume
    user_db_vault_creds:
        name: user_db_creds_volume
    interview_store_db_vault_creds:
        name: svc_interview_store_db_creds_volume
    grading_db_vault_creds:
        name: grading_db_vault_creds_volume
    grafana_vault_creds:
        name: grafana_vault_creds_volume

    # VAULT VOLUMES
    vault_data:
        name: vault_data_volume
    vault_tls:
        name: vault_tls_volume
    vault_logs:
        name: vault_logs_volume
    vault_init:
        name: vault_init_volume
    frontend_tls:
        name: frontend_tls_volume
