# Local minimal OWASP CRS setup.
# PL1 blocks. PL2 is executed for observation/tuning.

SecAction \
 "id:900000,\
  phase:1,\
  pass,\
  nolog,\
  setvar:tx.paranoia_level=1"

SecAction \
 "id:900001,\
  phase:1,\
  pass,\
  nolog,\
  setvar:tx.executing_paranoia_level=2"

SecAction \
 "id:900110,\
  phase:1,\
  pass,\
  nolog,\
  setvar:tx.inbound_anomaly_score_threshold=5,\
  setvar:tx.outbound_anomaly_score_threshold=4"

SecAction \
 "id:900990,\
  phase:1,\
  pass,\
  nolog,\
  setvar:tx.crs_setup_version=330"