Include /etc/nginx/modsecurity/modsecurity.conf

# Local CRS setup to avoid SecDefaultAction conflicts.
Include /etc/nginx/modsecurity/crs-setup.conf

# OWASP Core Rule Set rules from Debian package.
Include /usr/share/modsecurity-crs/rules/*.conf
