FROM node:25-bookworm-slim

WORKDIR /workdir

RUN apt update && apt install -y \
    git \
    curl \
    bash \
    && rm -rf /var/lib/apt/lists/*

# Default port for NodeJS Express servers
EXPOSE 3000

# Default port for Vite dev servers
EXPOSE 5173

